In [572]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from warnings import filterwarnings
filterwarnings('ignore')
from sklearn import metrics as sm
from sklearn import preprocessing as sp

In [573]:
df = pd.read_csv('Titanic-Dataset.csv')

In [574]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [575]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [576]:
df['Age'].median()

np.float64(28.0)

In [577]:
df['Age']=df['Age'].fillna(df['Age'].median())

In [578]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [579]:
df['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [580]:
df = df.drop(columns = ['Cabin']).dropna()

In [581]:
X_train, X_test, Y_train, Y_test = train_test_split(df.drop(columns = ['Survived']), df['Survived'], test_size=0.2,random_state=42)

In [582]:
X_train

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
708,709,1,"Cleaver, Miss. Alice",female,22.0,0,0,113781,151.5500,S
240,241,3,"Zabour, Miss. Thamine",female,28.0,1,0,2665,14.4542,C
382,383,3,"Tikkanen, Mr. Juho",male,32.0,0,0,STON/O 2. 3101293,7.9250,S
792,793,3,"Sage, Miss. Stella Anna",female,28.0,8,2,CA. 2343,69.5500,S
683,684,3,"Goodwin, Mr. Charles Edward",male,14.0,5,2,CA 2144,46.9000,S
...,...,...,...,...,...,...,...,...,...,...
107,108,3,"Moss, Mr. Albert Johan",male,28.0,0,0,312991,7.7750,S
271,272,3,"Tornquist, Mr. William Henry",male,25.0,0,0,LINE,0.0000,S
862,863,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,S
436,437,3,"Ford, Miss. Doolina Margaret ""Daisy""",female,21.0,2,2,W./C. 6608,34.3750,S
103,104,3,"Johansson, Mr. Gustaf Joel",male,33.0,0,0,7540,8.6542,S

In [583]:
#X_train['Ticket_Cat'] = X_train['Ticket'].apply(lambda x : 0 if x.isnumeric() else 1)

In [584]:
#X_test['Ticket_Cat'] = X_test['Ticket'].apply(lambda x : 0 if x.isnumeric() else 1)

In [585]:
X_train.drop(columns = ['PassengerId', 'Name', 'Ticket'], inplace=True)

In [586]:
X_test.drop(columns = ['PassengerId', 'Name', 'Ticket'], inplace=True)

In [587]:
X_train = X_train.merge(pd.get_dummies(X_train[['Sex', 'Embarked']], drop_first=True, dtype=int), left_index=True, right_index=True).drop(columns = ['Sex', 'Embarked'])

In [588]:
X_test = X_test.merge(pd.get_dummies(X_test[['Sex', 'Embarked']], drop_first=True, dtype=int), left_index=True, right_index=True).drop(columns = ['Sex', 'Embarked'])

In [589]:
X_train.describe()

,Pclass,Age,SibSp,Parch,Fare,Sex_male,Embarked_Q,Embarked_S
count,711.000000,711.000000,711.000000,711.000000,711.000000,711.000000,711.000000,711.000000
mean,2.322082,29.511730,0.554149,0.382560,32.060354,0.663854,0.091421,0.722925
std,0.835180,13.144679,1.168643,0.804865,49.195227,0.472722,0.288409,0.447869
min,1.000000,0.420000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.000000,22.000000,0.000000,0.000000,7.895800,0.000000,0.000000,0.000000
50%,3.000000,28.000000,0.000000,0.000000,14.500000,1.000000,0.000000,1.000000
75%,3.000000,36.000000,1.000000,0.000000,30.695800,1.000000,0.000000,1.000000
max,3.000000,80.000000,8.000000,6.000000,512.329200,1.000000,1.000000,1.000000

In [590]:
X_train['Age'].value_counts()

Age
28.00    164
24.00     24
22.00     22
21.00     21
19.00     21
        ...
74.00      1
70.00      1
0.67       1
23.50      1
57.00      1
Name: count, Length: 85, dtype: int64

In [591]:
X_train['Age'].astype(int)

708    22
240    28
382    32
792    28
683    14
       ..
107    28
271    25
862    48
436    21
103    33
Name: Age, Length: 711, dtype: int64

In [592]:
X_train[X_train['Age'] < 10]

     Pclass   Age  SibSp  Parch      Fare  Sex_male  Embarked_Q  Embarked_S
119       3  2.00      4      2   31.2750         0           0           1
261       3  3.00      4      2   31.3875         1           0           1
7         3  2.00      3      1   21.0750         1           0           1
813       3  6.00      4      2   31.2750         0           0           1
182       3  9.00      4      2   31.3875         1           0           1
469       3  0.75      2      1   19.2583         0           0           0
165       3  9.00      0      2   20.5250         1           0           1
381       3  1.00      0      2   15.7417         0           0           0
445       1  4.00      0      2   81.8583         1           0           1
24        3  8.00      3      1   21.0750         0           0           1
183       2  1.00      2      1   39.0000         1           0           1
164       3  1.00      4      1   39.6875         1           0           1
827       2  1.00      0      2   37.0042         1           0           0
43        2  3.00      1      2   41.5792         0           0           0
479       3  2.00      0      1   12.2875         0           0           1
549       2  8.00      1      1   36.7500         1           0           1
278       3  7.00      4      1   29.1250         1           1           0
237       2  8.00      0      2   26.2500         0           0           1
803       3  0.42      0      1    8.5167         1           0           0
530       2  2.00      1      1   26.0000         0           0           1
824       3  2.00      4      1   39.6875         1           0           1
480       3  9.00      5      2   46.9000         1           0           1
305       1  0.92      1      2  151.5500         1           0           1
50        3  7.00      4      1   39.6875         1           0           1
831       2  0.83      1      1   18.7500         1           0           1
172       3  1.00      1      1   11.1333         0           0           1
16        3  2.00      4      1   29.1250         1           1           0
751       3  6.00      0      1   12.4750         1           0           1
644       3  0.75      2      1   19.2583         0           0           0
788       3  1.00      1      2   20.5750         1           0           1
489       3  9.00      1      1   15.9000         1           0           1
147       3  9.00      2      2   34.3750         0           0           1
184       3  4.00      0      2   22.0250         0           0           1
787       3  8.00      4      1   29.1250         1           1           0
642       3  2.00      3      2   27.9000         0           0           1
233       3  5.00      4      2   31.3875         0           0           1
374       3  3.00      3      1   21.0750         0           0           1
750       2  4.00      1      1   23.0000         0           0           1
348       3  3.00      1      1   15.9000         1           0           1
850       3  4.00      4      2   31.2750         1           0           1
541       3  9.00      4      2   31.2750         0           0           1
171       3  4.00      4      1   29.1250         1           1           0
691       3  4.00      0      1   13.4167         0           0           0
755       2  0.67      1      1   14.5000         1           0           1
407       2  3.00      1      1   18.7500         1           0           1
63        3  4.00      3      2   27.9000         1           0           1
720       2  6.00      0      1   33.0000         0           0           1
340       2  2.00      1      1   26.0000         1           0           1
777       3  5.00      0      0   12.4750         0           0           1
58        2  5.00      1      2   27.7500         0           0           1
386       3  1.00      5      2   46.9000         1           0           1

In [593]:
Y_train.loc[X_train[(X_train['Age'] < 35) & (X_train['Age'] > 25)].index].sum()

np.int64(95)

In [594]:
def categorize(x):
    if(x < 5):
        return 1
    if(x < 15):
        return 2
    if(x < 20):
        return 3
    if(x < 25):
        return 4
    if(x < 30):
        return 5
    if(x < 35):
        return 6
    if(x < 40):
        return 7
    if(x < 50):
        return 8
    if(x < 60):
        return 9
    if(x >= 60):
        return 10

In [595]:
#X_train['Age']=X_train['Age'].apply(categorize)

In [596]:
#X_test['Age'] = X_test['Age'].apply(categorize)

In [597]:
X_train

     Pclass   Age  SibSp  Parch      Fare  Sex_male  Embarked_Q  Embarked_S
708       1  22.0      0      0  151.5500         0           0           1
240       3  28.0      1      0   14.4542         0           0           0
382       3  32.0      0      0    7.9250         1           0           1
792       3  28.0      8      2   69.5500         0           0           1
683       3  14.0      5      2   46.9000         1           0           1
..      ...   ...    ...    ...       ...       ...         ...         ...
107       3  28.0      0      0    7.7750         1           0           1
271       3  25.0      0      0    0.0000         1           0           1
862       1  48.0      0      0   25.9292         0           0           1
436       3  21.0      2      2   34.3750         0           0           1
103       3  33.0      0      0    8.6542         1           0           1

[711 rows x 8 columns]

In [598]:
X_test

     Pclass   Age  SibSp  Parch      Fare  Sex_male  Embarked_Q  Embarked_S
281       3  28.0      0      0    7.8542         1           0           1
435       1  14.0      1      2  120.0000         0           0           1
39        3  14.0      1      0   11.2417         0           0           0
418       2  30.0      0      0   13.0000         1           0           1
585       1  18.0      0      2   79.6500         0           0           1
..      ...   ...    ...    ...       ...       ...         ...         ...
433       3  17.0      0      0    7.1250         1           0           1
807       3  18.0      0      0    7.7750         0           0           1
25        3  38.0      1      5   31.3875         0           0           1
85        3  33.0      3      0   15.8500         0           0           1
10        3   4.0      1      1   16.7000         0           0           1

[178 rows x 8 columns]

In [599]:
lr = LogisticRegression(C=100000000)

In [600]:
lr.fit(X_train, Y_train)

LogisticRegression(C=100000000)

In [601]:
lr.score(X_train, Y_train)

0.8002812939521801

In [602]:
lr.score(X_test, Y_test)

0.7808988764044944

In [603]:
sm.balanced_accuracy_score(Y_train,lr.predict(X_train))

0.7826526333445152